on:
  schedule:
    # https://crontab.guru/#0_0_*_*_*
    # At 00:00 (UTC)
    - cron: "0 0 * * *"
  workflow_dispatch: # allow manually running
    inputs:
      log_level:
        type: choice
        options:
          - NOTSET
          - DEBUG
          - INFO
          - WARNING
          - ERROR
        default: INFO

env:
  FORCE_COLOR: 1

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - uses: astral-sh/setup-uv@v5.2.1
        with:
          enable-cache: true
          version: "0.5.21"

      - env:
          LOG_LEVEL: ${{ inputs.log_level }}
        run: uv run pointer-io-rssfeed

      # TODO: publish (gist? github release? push to a branch?)
